### ISSUE TITLE
Make the website responsive

### ISSUE THREAD

**Issue by DiegoEliasCosta** [REALISELab/REALISELab.github.io#1]
The site is currently not responsive on mobile devices. 

This is a high-priority issue! We should avoid customized divs/panels and mostly use Docusaurus capabilities to ensure the website can be accessed in various screen sizes.

**Comment by MohamedBilelBesbes** [comment]
Responsiveness issues fixed and pushed to prod. I will include the dark mode changes in the scope of this issue as well, right now there some fixes to be done in the dark mode setup for Partners page, Partners section of the main page, and the Project page, I'll close this github issue once I fix those problems.

**Comment by MohamedBilelBesbes** [comment]
dark mode issue fixed in Partners page, Projects page, and Partners section in main page. Closing this ticket.

**Comment by DiegoEliasCosta** [comment]
The website is much better now, but the text in the front page does not load well in mobile. 
- The text is not left-aligned and the bullet point looks off. 

The core issue, I believe, is that we are editing the jsx file, which is not meant to be used as a source of content.
