### ISSUE TITLE
Create an exemplary profile page with the picture on the left side

### ISSUE THREAD

**Issue by DiegoEliasCosta** [REALISELab/REALISELab.github.io#3]
Could we have the profile page (under Teams) show the profile page on the left side?
This is more like an enhancement of the profile page, which, I think, would make it a bit better. 

If we can do that, then we would ask students to copy from this exemplary page.

**Comment by gencau** [comment]
I’ve created something that looks like what is requested in this PR on my profile page. Please take a look and let me know if that’s what you want. Otherwise we can adjust it.

**Comment by DiegoEliasCosta** [comment]
It looks good, thanks @gencau! Although, on mobile it does not seem to work well. @MohamedBilelBesbes do you know why?

**Comment by MohamedBilelBesbes** [comment]
I think that the main reason is that Gen's page contains HTML components with custom CSS, supposedly if everything is in MD/MDX, the template would work fine in responsive mode

**Comment by gencau** [comment]
What I see is that it is responsive, in that the text doesn't overflow the page, however the image is displayed centered (vertically) instead of at the top of the text, and the text does not nicely wrap right underneath it. Is that also what you see @DiegoEliasCosta?

**Comment by DiegoEliasCosta** [comment]
Yeah @gencau. It is not a big deal, but on profiles where there is more text, it is difficult to follow on a mobile.  

I dont think this can be solved with MD support (unless we apply an invisible table?) but I am not super familiar with MDX capabilities. @MohamedBilelBesbes can you try seeing whether there is anything that supports the layout in MDX?
